"""Stable error codes for Data_Fetcher_Ubuntu."""


class ErrorCode:
    """Stable machine-readable error codes."""

    # Acquisition
    SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
    CHECKSUM_MISMATCH = "CHECKSUM_MISMATCH"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"

    # Processing
    EXTRACTION_FAILED = "EXTRACTION_FAILED"
    NORMALIZATION_FAILED = "NORMALIZATION_FAILED"

    # Dataset
    DATASET_SPEC_INVALID = "DATASET_SPEC_INVALID"
    DATASET_INFEASIBLE = "DATASET_INFEASIBLE"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    EXPORT_FAILED = "EXPORT_FAILED"

    # Infrastructure
    STORAGE_UNAVAILABLE = "STORAGE_UNAVAILABLE"
    DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE"

    # Governance
    RIGHTS_REVIEW_REQUIRED = "RIGHTS_REVIEW_REQUIRED"
